server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://192.168.0.133:5432/taskr
    username: postgres
    password: postgres
  rabbitmq:
    host: 192.168.0.133
    port: 5672
    username: bhavanichandra
    password: mdeveloper@123
    queue: taskr-queue
    exchange: taskr-api
springdoc:
  swagger-ui:
    path: /docs
